name: Weekly Triage assignment

on:
    workflow_dispatch

jobs:
    create-issue:
        runs-on: ubuntu-latest
        if: github.repository_owner == 'bryceosterhaus'
        steps:
            - id: get-day
              run: echo "::set-output name=DAY::$(date +%d)"

            - name: Create Issue
              env:
                  ASSIGNEE: ${{ (steps.get-day.outputs.DAY < 10 &&  'bryceosterhaus') || (steps.get-day.outputs.DAY < 20 && 'izaera') || 'bryceosterhaus' }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  gh issue create --repo $GITHUB_REPOSITORY \
                  --title "Weekly Issue Triage" \
                  --assignee $ASSIGNEE \
                  --body \
                  "Hey @$ASSIGNEE, It's that time of the week. Go through our issue backlog and triage by closing and adding labels."
