name: 'Conventional Commits'

on:
    pull_request_target:
        types:
            - opened
            - edited
            - synchronize

jobs:
    main:
        name: Validate PR title
        runs-on: ubuntu-latest
        steps:
            - uses: amannn/action-semantic-pull-request@v4
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    validate-commits:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v1
            - name: Commitsar check
              uses: aevea/commitsar@v0.18.0
