name: Dependencies Update

on: workflow_dispatch

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
          - name: Fetch release version
            id: fetch-latest
            run: |
                curl -sL https://api.github.com/repos/liferay/liferay-portal/releases/latest | \
                jq -r ".tag_name" | xargs -I {} echo "::set-output name=LATEST_RELEASE::{}"

          - name: Write file
            run: echo "${{ steps.fetch-latest.outputs.LATEST_RELEASE }}" > portal-release.txt

          - name: Cache Latest Portal Release Version
            uses: actions/cache@v2
            id: cache-version
            with:
              path: ./portal-release.txt
              key: ${{ steps.fetch-latest.outputs.LATEST_RELEASE }}


          - name: Create Issue
            if: ${{ steps.cache-version.outputs.cache-hit != 'true' }}
            run: echo "CREATING A NEW ISSUE"
