name: Dependencies Update

on: workflow_dispatch

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Fetch release version
              id: fetch-latest
              run: |
                  curl -sL https://api.github.com/repos/liferay/liferay-portal/releases/latest | \
                  jq -r ".tag_name" | xargs -I {} echo "::set-output name=LATEST_RELEASE::{}"
            - name: Write artifcat
              run: |
                  echo "${{ steps.fetch-latest.outputs.LATEST_RELEASE }}" | > portal-release.txt
            - name: Download a single artifact
              uses: actions/download-artifact@v2
              with:
                  name: portal-release
            - name: 'Upload Artifact'
              uses: actions/upload-artifact@v2
              with:
                  name: portal-release
                  path: portal-release.txt
            - name: Create Issue
              if: cat portal-release.txt | xargs -n2 sh -c 'test $1 = "${{ steps.fetch-latest.outputs.LATEST_RELEASE }}"
              run: echo "CREATING ISSUE"
